### ISSUE TITLE
Use Cases as Issues?

### ISSUE THREAD

**Issue by erinspace** [CenterForOpenScience/SHARE#135]
I was wondering, might we move all of the "Use Case" discussions currently on the issue list to a section on the wiki? It seems as if they'd be more useful there, as points of reference and places where they can be added to, as opposed to a granular event that can be closed. 

@efc do you have thoughts on this?

**Comment by efc** [comment]
@erinspace, I have no objection to that plan. I put the [Use Case](https://github.com/CenterForOpenScience/SHARE/labels/NS%20use%20case) items into issues back in August because Andrew thought they would be more useful to the dev team there. If the wiki makes more sense, that's OK by me. Note that we also have more recent User Stories that we can refer to from whatever Use Case page we set up in the wiki.

**Comment by erinspace** [comment]
Great! 

I've made a draft page on the wiki with the information from the use case issues - 
https://github.com/CenterForOpenScience/SHARE/wiki/Use-Cases

If this looks ok to everyone I'll go ahead and close those use case issues.

**Comment by efc** [comment]
@erinspace, I should have thought of this before... Since these use cases were transcribed into the issues at COS request, there is actually the earlier version [still on Google Docs](https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit?usp=sharing). I think it makes more sense to point people to that Google Doc version than to create a third version in the wiki. Easier too. The Google Doc also has the advantage of accepting comments.

So let me contradict myself. I think instead of setting these up on the wiki we should just have a link from the wiki to [the Use Case document](https://docs.google.com/document/d/1gqVDZsD4wpGpBAYNf428YB0XQ6QBlGt32B_2IiQqkiA/edit?usp=sharing) we already have in place.

**Comment by erinspace** [comment]
Got it! Document linked and added to the wiki, will close the use case issues. Thanks!
