### ISSUE TITLE
DataONE looking for certificate to resolve URL

### ISSUE THREAD

**Issue by efc** [CenterForOpenScience/SHARE#144]
I was just exploring some DataONE events in the SHARE Notification Service when I realized I could not actually click through to their representations on DataONE itself. The illustration below shows what I ran into when trying to get to http://share.clst.org/id/54daa123fcdd1d0a7777dad9 (using my demo SHARE tool). The URL provided on this record is https://cn.dataone.org/cn/v1/resolve/knb-lter-gce.266.23, but this URL demands a certificate I do not have.

This record is also marked ```"isPublic": "true"``` in the other elements from DataONE, so it appears it should be publicly accessible.

Any thoughts on why the cert challenge is being issued? I will alert David at DataONE to take a peek at this issue, since I imagine the answer lies on their end. As far as I can tell, this applies to many (if not all) DataONE entries.

![screen shot 2015-02-11 at 8 41 47am](https://cloud.githubusercontent.com/assets/604967/6148777/dc918e60-b1c9-11e4-92ad-4ddc17960b05.PNG)

**Comment by vdave** [comment]
This is a known issue with the Safari browser and how it handles server requests for optional client certificates. The browser should continue without requiring a certificate if none is defined for use with the target. Unfortunately, Safari looks in your keychain, and if any client certificates are present then it asks which one you want to use. There is no known fix for this issue and Apple is unlikely to correct it since it has been known for at least a couple years. You can use a different browser or press "Cancel" and the connection should continue as expected.

**Comment by efc** [comment]
Sure enough, @vdave, this does not happen in Chrome. I must have not been using Safari the last few times I poked at DataONE records. Thank you.

Team: I wonder if we will need our own "known issues" list to remember things like this in case others ask us downstream?
